Implement Page header
tiborFulop123/todoapp pull request #1
Opened 2023-02-01 09:32 UTC by tiborFulop123

2023-02-01 11:37 UTC, roli-wg requested changes

2023-02-01 11:37 UTC, roli-wg commented on src/components/HeaderComponent.vue
> +      </span><input type="text" v-model="todoText" />
The header doesn't have any input in the design so please remove unnecessary or unused html tags

2023-02-01 11:37 UTC, roli-wg commented on src/components/HeaderComponent.vue
> +   <TodoForm     @toDoAdded="addNewTodo">   </TodoForm> -->
It is not a good practice to leave commented code in your work once you think that all the functionality and requirements are in place you don't anymore need this commented parts so please make sure to remove all the commented code in all your files

2023-02-01 11:37 UTC, roli-wg commented on src/components/HeaderComponent.vue
> +}
Please make sure that you import and declare only the components and variables which you actually using. Try to keep your code clean so please remove all the unnecessary imports, variables and functions if are any

2023-02-01 11:37 UTC, roli-wg commented on src/components/HeaderComponent.vue
> +// // const emit = defineEmits(["toDoAdded"])
Remove all commented code

2023-02-01 11:37 UTC, roli-wg commented on src/components/HeaderComponent.vue
> +}
Try to use tailwind css for styling whenever you can. 
Please change all this styles with tailwind classes

2023-02-01 11:37 UTC, roli-wg commented on src/components/HelloWorld.vue
> +  <div>    </div>
Please remove empty html tags

2023-02-01 11:37 UTC, roli-wg commented
Will make an exception and refrain from reviewing code other than the Header task related.

2023-02-01 11:37 UTC, roli-wg commented
Please add prettier and use prettier on this project with the following configuration:
`
{
"singleQuote": true,
"useTabs": false,
"tabWidth": 2,
"vueIndentScriptAndStyle": true
}

`

2023-02-02 07:52 UTC, komaromiGyorgy approved these changes

2023-02-02 07:52 UTC, komaromiGyorgy commented on src/components/HomePage.vue
> +  import toDoListMT from './../assets/toDoListMT.svg';
Can you give a more explicit name to this image? It is not very clear what this image is from the name of it, something like todoListPlaceholder

2023-02-03 07:27 UTC, roli-wg approved these changes

2023-02-03 07:27 UTC, merged