ITl-5 Implement Search Functionality
tiborFulop123/todoapp pull request #5
Opened 2023-03-13 08:17 UTC by tiborFulop123

2023-03-13 08:50 UTC, gerebdavid commented on src/components/HomePage.vue
> +  const searchedToDo = computed(() => {
const searchedToDo = computed(() => toDos.value.filter((item) => item.title.includes(searchTitle.value)));

2023-03-13 08:51 UTC, gerebdavid commented on src/components/ToDoListSearch.vue
> +      <button class="m-2 bg-black text-white rounded-full" @click="searchToDo">
Can you use the baseButton here?

2023-03-13 08:51 UTC, gerebdavid commented on src/components/HomePage.vue
> +    console.log(searchText);
Do you still need this console.log?

2023-03-13 08:52 UTC, gerebdavid commented on src/components/ToDoListSearch.vue
> +  import { ref } from 'vue';
First imports from vue and the the icon

2023-03-13 11:40 UTC, kincsokiss requested changes

2023-03-13 11:40 UTC, kincsokiss commented on src/components/Header.vue
> +    console.log(searchField);
Please add descriptive log message here, not just the value, or remove this line.

2023-03-14 12:43 UTC, gerebdavid approved these changes

2023-03-15 08:07 UTC, roli-wg approved these changes

2023-03-15 08:09 UTC, komaromiGyorgy approved these changes

2023-03-15 09:17 UTC, kincsokiss approved these changes

2023-03-15 11:28 UTC, merged